## LAB : 1
## Aim : BASIC TOOLS/TEHCNIQUES NEEDED IN ML/DLL

In [3]:
print(8)

8


In [4]:
a=5
b="abc"
c=1.01

In [5]:
print(a,b,c)

5 abc 1.01


In [6]:
print(type(a),type(b),type(c))

<class 'int'> <class 'str'> <class 'float'>


In [7]:
type(a),type(b),type(c)

(int, str, float)

In [8]:
a,b,c

(5, 'abc', 1.01)

# operator

In [9]:
n1=5
n2=5
print(n1/n2)
print(n1//n2)
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1**n2)

1.0
1
10
0
25
3125


# condition

In [10]:
if(n1>n2):
    print(n1,":n1 is big")
elif(n2>n1):
    print(n2,":n2 is big")
elif(n1 is n2):
    print("both are same")

both are same


# loop

In [11]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [12]:
i=0
while(i<10):
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9


# composite data type

In [13]:
#mutable : list
arr=[1,3,4,'abc',3.0,7]
print(arr)
for i in range(0,len(arr)):
    print(arr[i])

[1, 3, 4, 'abc', 3.0, 7]
1
3
4
abc
3.0
7


In [14]:
#immutable :tuple
tp=(1,2,5,4.5,'bcd',2)
print(tp)
for i in tp:
    print(i)

(1, 2, 5, 4.5, 'bcd', 2)
1
2
5
4.5
bcd
2


In [15]:
#key value pair :dictionary
kv={'name':'arpan','rno':120}
print(kv)

{'name': 'arpan', 'rno': 120}


In [16]:
arr[0:-1:2]

[1, 4, 3.0]

# function

In [17]:
def summation(a,b):
    return a+b;

summation(3,2)


5

In [18]:
def Fibonacci(n):
    if n < 0:
        print("Incorrect input")

    elif n == 0:
        return 0
 
    elif n == 1 or n == 2:
        return 1
 
    else:
        return Fibonacci(n-1) + Fibonacci(n-2)
 
print(Fibonacci(9))

34


In [19]:
def rec(n):
    if n < 0:
        print("Incorrect input")
 
    elif n == 0 or n == 1:
        return 1
 
    else:
        return n*rec(n-1)
 
print(rec(5))

120


# pip command

In [20]:
#pip --help
#for help

In [21]:
# pip list (for list of packages and his versions)

# Numpy

In [22]:
pip install numpy

In [23]:
import numpy as np

In [24]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [25]:
arr[1]

20

In [26]:
arr[-1]

50

In [27]:
arr[1:-1]

array([20, 30, 40])

In [28]:
arr[-3:]

array([30, 40, 50])

In [29]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
b[0,2]

3

In [31]:
b[0:2,2]

array([3, 6])

In [32]:
arr[0]

10

In [33]:
arr[2:]

array([30, 40, 50])

In [34]:
arr[:3]

array([10, 20, 30])

In [35]:
arr[-1]

50

In [36]:
arr[-3:]

array([30, 40, 50])

In [37]:
arr[1:2]

array([20])

In [38]:
b[0,2]

3

In [39]:
b[0,:]

array([1, 2, 3])

In [40]:
b[1,:]

array([4, 5, 6])

In [41]:
b[1:2,0:1]

array([[4]])

In [42]:
b[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [43]:
b.shape


(3, 3)

# matrix operations

In [44]:
c=np.array([[1,2,4],[4,5,6],[7,8,9]])
b+c

array([[ 2,  4,  7],
       [ 8, 10, 12],
       [14, 16, 18]])

In [45]:
b-c

array([[ 0,  0, -1],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [46]:
b*c

array([[ 1,  4, 12],
       [16, 25, 36],
       [49, 64, 81]])

In [47]:
b/c

array([[1.  , 1.  , 0.75],
       [1.  , 1.  , 1.  ],
       [1.  , 1.  , 1.  ]])

In [48]:
b//c

array([[1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
b**c

array([[        1,         4,        81],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [50]:
np.dot(b,c)

array([[ 30,  36,  43],
       [ 66,  81, 100],
       [102, 126, 157]])

In [51]:
np.transpose(b)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
np.cross(b,c)

array([[ 2, -1,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [53]:
np.sin(b)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [54]:
np.exp(b)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [55]:
np.log(b)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [56]:
np.abs(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
d=np.random.uniform(size=4).reshape(2,2)
np.floor(d*4)

array([[1., 0.],
       [3., 0.]])

DATASERIES AND DATAFRAME

In [2]:
import pandas as pd
ds = pd.Series([10,20,30]);
ds

0    10
1    20
2    30
dtype: int64

In [3]:
ds[0]

10

In [4]:
ds = pd.Series([10,20,30],index= ["A","B","C"]);
ds

A    10
B    20
C    30
dtype: int64

In [5]:
ds["B"]

20

In [6]:
ds[0:2]

A    10
B    20
dtype: int64

In [7]:
ds["A"],ds["B"]

(10, 20)

In [8]:
ds[ds>10]

B    20
C    30
dtype: int64

In [9]:
ds[ds==10]

A    10
dtype: int64

In [10]:
df = pd.DataFrame(([10,20,30],[40,50,60]),columns=['A','B','C'],dtype=int)
df

A   B   C
0  10  20  30
1  40  50  60

In [11]:
df.A

0    10
1    40
Name: A, dtype: int32

In [12]:
dict = { "name":['A','B','C'] , "age" : [20,30,40]}
dict

{'name': ['A', 'B', 'C'], 'age': [20, 30, 40]}

In [13]:
df = pd.DataFrame(dict)
df

name  age
0    A   20
1    B   30
2    C   40

In [14]:
df['weight']=[60,90,100]
df

name  age  weight
0    A   20      60
1    B   30      90
2    C   40     100

In [15]:
student = {"id":[1,2,3,4,5] , "name" : ["A","B","C","D","E"] ,"address":["A11","B11","C11","D11","E11"] , "marks1" : [30,40,50,60,70], "marks2" : [40,50,60,70,80]}

In [16]:
df = pd.DataFrame(student)
df

id name address  marks1  marks2
0   1    A     A11      30      40
1   2    B     B11      40      50
2   3    C     C11      50      60
3   4    D     D11      60      70
4   5    E     E11      70      80

In [17]:
df['total']=[70,90,110,130,150]

In [18]:
df

id name address  marks1  marks2  total
0   1    A     A11      30      40     70
1   2    B     B11      40      50     90
2   3    C     C11      50      60    110
3   4    D     D11      60      70    130
4   5    E     E11      70      80    150

In [19]:
df.iloc[:2,0:1]

id
0   1
1   2

In [20]:
df.loc[:2,'id']

0    1
1    2
2    3
Name: id, dtype: int64